site_name: K-9 Mail
repo_url: https://github.com/k9mail/k9mail-docs
edit_uri: edit/main/docs/
theme: material
markdown_extensions:
  - toc
nav:
  - Welcome: en/current/index.md
  - Setup:
    - Installation: en/current/setup/installation.md
    - Initial Set-up: en/current/setup/welcome.md
    - App permissions: en/current/setup/permissions.md
  - Accounts: 
    - Adding an Account: en/current/accounts/add.md
    - IMAP Server Settings: en/current/accounts/incoming_imap.md
    - POP3 Server Settings: en/current/accounts/incoming_pop3.md
    - Outgoing Server Settings: en/current/accounts/outgoing.md
    - Managing / Viewing Accounts:
        - Adding another account: en/current/accounts/add_another.md
        - Switching Accounts: en/current/accounts/switching.md
        - Removing Accounts: en/current/accounts/remove.md
  - Reading:
    - Reading mail: en/current/reading/reading.md
    - Managing mail: en/current/reading/managing.md
    - Notifications: en/current/reading/notifications.md
  - Sending:
    - Starting to Compose an E-mail: en/current/sending/sending_start.md
    - Editing E-mail Content: en/current/sending/sending_content.md
  - Settings:
    - Settings Overview: en/current/settings/overview.md
    - General settings: en/current/settings/general.md
    - Account settings: en/current/settings/account.md
    - Push settings: en/current/settings/push.md
    - Folder settings: en/current/settings/folder.md
    - Export settings: en/current/settings/export.md
    - Import settings: en/current/settings/import.md
    - Folder classes: en/current/settings/folder_classes.md
  - Security:
    - Overview: en/current/security/overview.md
    - PGP: en/current/security/pgp.md
  - Miscellaneous:
    - Widgets: en/current/misc/widgets.md
    - Debugging: en/current/misc/debugging.md
    - Frequently asked questions: https://forum.k9mail.app/c/faq/6
extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - redirects:
      redirect_maps:
        'index.md': 'en/current/index.md'
